services:
  - docker

language: generic

script:
  - make build

after_success:
  - docker login -u $DOCKER_USER -p $DOCKER_PASS
  - export REPO=oinker/oinker-api
  - export TAG=`if [ "$TRAVIS_BRANCH" == "master" ]; then echo "latest"; else echo $TRAVIS_BRANCH ; fi`
  - docker build -f Dockerfile -t $REPO:$COMMIT .
  - docker tag $REPO:$COMMIT $REPO:$TAG
  - docker push $REPO

env:
  global:
    - secure: "HR9B8GqfRGzstHyJS2PN1SYvd/LxIOvAGI77qm45aKmkHVqKDtcLm1F/f4EHVrvK6yrFYyeGgyFHxZkIJ8Zecdrbkq1Byk/RxS0ACCpmQwrPrs2XZNZPIWwcJOQILySb/1iDCv1ua6N3CUwyJjo07WzDFICdWIs4vtgglbb70RiSC7VluwyDCdg0IyxN5X3uMjlPMJxVbjaGyTHEpKjhWBeozm6ZHiR4ePRMLj7syCOQdmDeek9XEYUgsJTh+h99Xx295IvrFA1tMDSiSSwz3OybLx/hVE6cCmq9Et0pcqU1Vnc1M9pJ4yOymkt0esJIc76UyL1Jn07og2YKU1bD2ablDfrpxtzETXmdp7C8a3RB662n7Qn8yTAuFtbHcV6DZPPvEv3CgONLcvhWzJWrf6p6Vs2aZD9e2gwTogt+037Nx3wsf6cDSMdeh8Ug1nviU1UFO/vDKPzwfyW546DOOPravSNe/RjwVWUBDYzwz99ePqvDA0+FzZ3IizKQeKq7XX/GuUWFHWWAY8PmbRm6UyVzSDqy+oZjNWSeuPL5F0ppzGV9vtuz+DdEj35PQh8TMMnvOE3KOs7W0UJrJHB7jJvtTZTjdGaXq1b2hOMp7PbibU/u3lXbKB2tdLRyPCw//3BQP2HrHJAIfR+ybZ+RMCLjrSMTVrR+pUgsa7+eiE4=" # DOCKER_EMAIL
    - secure: "XrCGoT+b7MdEYdgeUd66BrnHXWcuXN9ThNrGPbTTxi9YGxjRiRnFKjp13D7O5fkIDebX/aHAhDQTXYxzIjhwSYVrJTDB/JDQ4m2FtydxpnUuJ9GoBEnJPShd/KYTwO1uWLClJbwXOk5hHBPm9Da/6Q1uysMJ5pzeqJRjOxjJiBr9yQmZcMeUBxfap97BHobFiPG92vHdWZmB6m3A6LiO+EBEXBYzvCc9EBIWqeUQGoxzKNBTj8SGBTfCvv8AS99SB1uY5yCdFqftXU6wP6qbuvb1PJUtPNO6W1KNGXnukEHEf78OKpTnRoV5OUEgTXPRHNyyMpCXZlSEbxQpP9NfB56An+lFS18IFfrafAJBmWe7VMRu/AYmBHJ2yM2wPW77+6fXDcjKGO5Q4iDb5+XQHwausvQnGGU1NPU8NsJzAZfSiVad/Tu1GMMDcN/yPsgOkEftUeyq1FeOAwI5SfrNFWFpxrNvf226XG1cE+8/kVAXQjY2xIzZCUDzp/0AJmDmStko3+8xFTFwWudbWalR4OWUII5pzdipCg6bLKD3YnTyzT0iw+hZgo3+Z7EZoCIL+HMAksUY3cUHAvQsygLDydFBxTFPCH4nzYMUoYyQUXZpeCMOErGF/2ubR4iLeos5Pj1D3Ben2zSWLjzOfD5GyWfJ+eWxxtyrJMrPQrp5t9c=" # DOCKER_USER
    - secure: "Q4BATbljQOAWLq/s71QlTb1jnUgqBXLuQAeUAW1rlMB5UmCKQGvUOmIo3vcO+vqkVc0nt61V/75+HSrutHN5ic1/tcpFysG+6Sf6dLGukpONKLUuG8duk9/xyYEGI7mexAtXUnGHsEHbJg7CPzpJnuX81yVQC/ucPUD/W8hFo6BTnDcjPCz0te42zpnIuqJrWritiINltzZ1ZZLCjTyonIKf4z3p+mW8DxDsxi3+PaM9ZpoIOQo2T73F8JbcK/hr+pWN17C7wSwfCFV0ncyAacpMkUtn8so+TaEQITtVfTgxLNX8Ql3Y1jtDxyeJoiBmWlMu2FvaH1uZ4wvoMn+NAV/XddDfFJJ5psjeJW7TbZNGo882TQwd6RBnhK5zB6wARDbYnANTse/e+O/q23vZcvmDaGP2zdT4Xy449CoT2mpmNlvg5iwZHNuBpF5J40WJ01OpTP5JxO3hDYErygNaf8ZK3317c95L/BEsBBTYi3TQiavjbODqmVjMWKCRoEpjoXafiHnB9Tp0J8Ia0kjolj/k1nv+AVl61R/e2EJYhBugGHuX6rtAmwg06HHWZa3NN9Z5qyroEmup4Q791ZvV/MuGhor1r8eLtzdWDKgtgouE76/YTHHAEjFYvJmsqrnNTwONrQXdm7TivSH1Vvn4/ZN+HGQEtMzkzOfQnYT9rBw=" # DOCKER_PASS
    - COMMIT=${TRAVIS_COMMIT::6}